# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_from', models.CharField(max_length=255)),
                ('starting_from_longitude', models.FloatField(null=True)),
                ('starting_from_latitude', models.FloatField(null=True)),
                ('going_to', models.CharField(max_length=255)),
                ('going_to_longitude', models.FloatField(null=True)),
                ('going_to_latitude', models.FloatField(null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('going_date', models.DateField()),
                ('going_time', models.TimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_members', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
